language: cpp

sudo: required

dist: xenial

compiler:
  - gcc  # [not osx]
  - clang  # [not linux]

os:
  - linux
  - osx

install:
    - source travis_install.sh

script:
  - mkdir ../build
  - cd ../build
  - cmake --debug-output -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DWITH_TESTS=YES ../radolan
  - make VERBOSE=1
